### ISSUE TITLE
Wildcards?

### ISSUE THREAD

**Issue by sergeevabc** [ddulesov/hashsum#1]
Dear Dmitry, the following sequence does not work, however is expected to work.

``` console
$ hashsum_win64 -v -t b3 *
(black line, no messages)

$ sha256sum *
7d0c2cfe0b6c43a66d36bbdaf00a383cd43cd2e2d187aa08ec9846bcdf663246 *hashsum_win64.exe
```

By the way, `-v` usually stands for the app’s version. Re-learning is stressful.

``` console
$ aria2c -v && dig -v && flac -v
aria2 version 1.35.0
DiG 9.11.6
flac 1.3.3
```

**Comment by ddulesov** [comment]
Yes. Asterisk command line expansion  on Windows in Microsoft (MSVC) specific feature. 
Unlike linux glibc, stdlib doesn't expand it by default. You can change this behaviour by linking project with setargv.obj (https://docs.microsoft.com/en-us/cpp/c-language/expanding-wildcard-arguments?view=msvc-160 )

Replacing `-v` with something else is good point. I think oposit  option `-q  --quiet` would prefer .  

Honesly, I am surprised by the attention to this project.  It was created  year ago only just to show that  blake3 outperform gost hash in in real-world scenarios. Both are crypto hashes so they are not suitable for tasks as file hashing

**Comment by sergeevabc** [comment]
> It was created year ago only just to show that blake3 outperform gost hash in in real-world scenarios.
> Both are crypto hashes so they are not suitable for tasks as file hashing.

Streebog (aka GOST 2012, not to be confused with obsolete 1994) is designed to be a slow cryptohash,
Blake3 is designed to be a fast cryptohash, their application areas are different.

As for file hashing, let me cite [the consensus][1]:
* accidental (e.g. network transmission, data rot) changes -> _non_-cryptohash xxHash (to replace CRC32)
* intentional (e.g. malicious) changes -> cryptohash Blake3 (to replace MD5/SHA1/SHA2/SHA3/Blake2 flavors)

The only trouble with Blake3 so far is that some implementations such as [enc_file][2] and [milva][3] (alas, including the very official one, [b3sum][4] by @oconnor663) suffer from a bad memory management. The one of yours works just fine, so keep going, Dmitry.

[1]: https://github.com/Cyan4973/xxHash/issues/479#issuecomment-801528938
[2]: https://github.com/LazyEmpiricist/enc_file/issues/25#issuecomment-811052020
[3]: https://github.com/samuel-lucas6/Milva/issues/1
[4]: https://github.com/BLAKE3-team/BLAKE3/issues/78#issuecomment-801425510

**Comment by ddulesov** [comment]
As for hash functions  you are absolutely right. XxHash is extrely fast  but not truly   cryptograthic hash function despite it is widely used in various blockhains.

**Comment by sergeevabc** [comment]
``` console
$ hashsum -t b3 *
```
![](https://i4.imageban.ru/out/2021/04/17/fa3e49198cb16dc7d39780f184aa781d.png)

**Comment by ddulesov** [comment]
Is it  window 64bit or x86, or maybe linux runnable under WSL?

**Comment by sergeevabc** [comment]
Windows 7, x64.

``` console
$ ver && hashsum_win_x64.exe -v
Microsoft Windows [Version 6.1.7601]
hashsum 0.1.1
```

**Comment by ddulesov** [comment]
It seems is caused by CPU capabilities. This runnables was built for AVX2 . Could you give me your CPU type?

**Comment by sergeevabc** [comment]
![](https://i3.imageban.ru/out/2021/04/18/f8017ed303015fe5df191bd5c7efe867.png)

**Comment by ddulesov** [comment]
Ok. I've replace windows executables with new ones. They require only SSE2 capable CPU

**Comment by sergeevabc** [comment]
Now wildcards work as expected. Thank you, Dmitry.
